### ISSUE TITLE
Error in pipeline when Deploying to Cloud Foundry

### ISSUE THREAD

**Issue by fifteentu** [IBM/watson-voice-bot#55]
Getting this error during pipeline when using the Deploy To Cloud Foundry for watson-voice-bot: 

   Downloading app package...
   Downloaded app package (1.6M)
   -----> Python Buildpack version 1.7.10
   -----> **Supplying Python
          **ERROR** Could not install python: no match found for 3.7.4 in [3.5.7 3.5.9 3.6.9 3.6.10 3.7.6 3.7.7 3.8.1 3.8.2]
   Failed to compile droplet: Failed to run all supply scripts: exit status 14**

I've found this re python-cloudpack: 
“Could not install python: no match found for 3.7.4 in [ ... ]”
https://github.com/cloudfoundry/python-buildpack/issues/158

Is there any quick hack/fix to make this Deploy To Cloud Foundry succeed?

**Comment by agavrin** [comment]
Change version. in runtime.txt to python-3.7.7

**Comment by tim-minter** [comment]
I got this issue too and changing to a new version fixed it however the deploy fails with no particular error:

```
Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs watson-voice-bot-xxxxx --recent' for more information
FAILED

Finished: FAILED
```

Any advice? Does the deploy have to be in a particular region? I deployed to London.

**Comment by markstur** [comment]
I'll fix the runtime version.

**Comment by markstur** [comment]
There is still a problem with the credentials.  There is a known problem with the assistant creds role, but I'm not sure why there is a problem with STT/TTS.  There is a workaround that works for both.

Go to the  Cloud Foundry App -> Runtime -> Environment Variables and add the Assistant, STT, and TTS creds (APIKey and URL) using the same key/values described for use in the local runtime .env.  We'll need to document this if we don't come up with an alternative.

Adding a screenshot here for now:

<img width="1625" alt="runtime_env" src="https://user-images.githubusercontent.com/7129103/85192034-e3bdb580-b275-11ea-9029-7481fd5e10b0.png">

**Comment by radua-ibm** [comment]
Similar issue re-occuring with `release.txt` currently set to `python-3.8.2` 

```
Supplying Python
          **ERROR** Could not install python: no match found for 3.8.2 in [3.5.7 3.5.9 3.6.10 3.6.11 3.7.7 3.7.8 3.8.3 3.8.5]
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
```

**Comment by Maureen-Sy** [comment]
The version has to be changed in runtime.txt to python-3.8.3
I changed it manually, but the deployment still fails (with no particular error, the same error has already been reported in July)

![github1](https://user-images.githubusercontent.com/71879703/94258949-fc510200-ff2d-11ea-9294-19132491b1b7.png)

Do have any advice for me how to fix it?

**Comment by markstur** [comment]
I've removed the runtime.txt so we should be able to keep running on 3.x without breaking every time a minor version goes away.  For the credentials workaround mentioned above, I created a separate issue.  It is still an issue w/ workaround.  Performance is still an issue for me too.
